name: "PR Triage"
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, locked]

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: "Assign Author to PR"
        uses: toshimaru/auto-author-assign@v1.3.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
